export const FETCH_COVID_DETAILS = "COVID_SUMMARY";
export const SET_COVID_DETAILS_LOADING = "SET_COVID_DETAILS_LOADING";
export const SORT_COVID_DETAILS = "SORT_COVID_DETAILS";
export const FILTER_COVID_DETAILS = "FILTER_COVID_DETAILS";
